---
- name: "Play for demoing Hello World Module"
  hosts: localhost
  gather_facts: false

  tasks:
    - name: "Hello World Demo"
      hello.world.hello_world:
        greet_name: "Cooper"
      register: hello_result

    - name: "Print greeting"
      ansible.builtin.debug:
        var: hello_result.result
