---
- name: "Play for demoing Hello from Powershell Module"
  hosts: localhost
  gather_facts: false

  tasks:
    - name: "Hello from Powershell Demo"
      hello.world.hello_pwsh:
        greet_name: "Murphy"
      register: hello_result

    - name: "Print greeting"
      ansible.builtin.debug:
        var: hello_result.result
